language: python
python: 3.6
cache: pip
install:
  - (cd slides && npm install)
  - pip install poetry
  - poetry install
script:
  - (cd slides && npm run webpack)
  - poetry run lektor build -f webpack
deploy:
  provider: script
  script: poetry run lektor deploy ghpages
  on:
    branch: develop
